### ISSUE TITLE
Target audiences of SDK, and verification tool for voters

### ISSUE THREAD

**Issue by augusto-herrmann** [microsoft/ElectionGuard-SDK#1]
What are the target audiences of the ElectionGuard SDK? From the README, I suppose that the main target audience for the SDK will be election technology experts and election officials, right?

From what I understand of the [blog post](https://blogs.microsoft.com/on-the-issues/2019/05/06/protecting-democratic-elections-through-secure-verifiable-voting/), the system will be end-to-end verifiable, and that presumes that not only it needs to be implemented by election authorities, but voters are also supposed to use an open source tool to verify, through homomorphic encryption calculations, whether or not their vote has been computed in the election results. It seems thus logical that it would have at least two separate open source tool sets:

* a back-end for election authorities to compute the votes
* a tool for voters to verify that their votes have been computed

Then, will the open source tool for voters also be released on Github, perhaps on another repo?

**Comment by joaquinperaza** [comment]
In many articles they mention that could be implementing for voting system, but also for third party verification systems.

**Comment by augusto-herrmann** [comment]
> In many articles they mention that could be implemented for voting systems, but also for third party verification systems.

Sure, there could be third party verification systems. But shouldn't there be a reference implementation from Microsoft? Especially considering that the systems' homomorphic encryption is probably not trivial to implement, and also the maxim from the cryptography space that "[you shouldn't roll your own crypto](https://security.stackexchange.com/questions/18197/why-shouldnt-we-roll-our-own#18198)".

**Comment by joaquinperaza** [comment]
"Second, ElectionGuard also includes an open specification – or a road map – which allows anyone to write an election verifier. Voters, candidates, news media and any observers can run verifiers of their own or downloaded from sources of their choosing to confirm tabulations are as reported. The combination of the tracker – which allows individual voters to verify that their votes have been accurately recorded – and the verifier – which allows anyone to verify that the recorded votes have been accurately counted – enables full “end-to-end verification” of the correctness of election results. It will not be possible to “hack” the vote without detection."

[https://blogs.microsoft.com/on-the-issues/2019/05/06/protecting-democratic-elections-through-secure-verifiable-voting/](url)

**Comment by augusto-herrmann** [comment]
@joaquinperaza yes, I have read that article, and my OP contains a link to it. Nevertheless, my point still stands.

Even with an open specification available you still need reference implementations. To illustrate, the W3C, whose job has been producing open specifications for decades, has a [process](https://www.w3.org/2004/02/Process-20040205/tr.html) that a proposed standard can't reach *recommendation* status (the final one) unless there is evidence of existing implementations.

**Comment by rc-ms** [comment]
Hello there and sorry to join this thread so late.  We are now live and, as you suggest, working on reference implementations across a variety of use cases.
